name: vuepress-depoly

on:
  push:
    branches:  
      - master 
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # checkout
    - name: checkout
      uses: actions/checkout@v2

    # setup python
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # generate configuration
    - name: install-vuepress
      run: |
        pip install pyyaml
        python .github/workflows/script/vuepress_config_generator.py
      
    # build
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: src/.vuepress/dist/
